apiVersion: v1
kind: Service
metadata:
  name: node-kub
  labels:
    app: nodeweb
spec:
  selector:
    app: nodeweb
  ports:
  - port: 8083
    protocol: TCP
    nodePort: 31000
  type: LoadBalancer
